import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@mui/material/Container";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { Box } from "@mui/material";
import MaterialThemeProvider from "@/components/materialThemeProvider/materialThemeProvider";
import { Suspense } from "react";
import Loading from "./loading";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <AppRouterCacheProvider>
          <MaterialThemeProvider>
            <Container maxWidth="lg">
              <Box minHeight="100vh">
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </Box>
            </Container>
          </MaterialThemeProvider>
        </AppRouterCacheProvider>
        <Footer />
      </body>
    </html>
  );
}
