import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@mui/material/Container";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { Box } from "@mui/material";
import MaterialThemeProvider from "@/components/materialThemeProvider/materialThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <MaterialThemeProvider>
          <Container>
            <Box minHeight="100vh">{children}</Box>
          </Container>
        </MaterialThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
